import { Post, CommentItem, UserProfile } from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'admin-akash-1',
    displayName: 'আকাশ (পরিচালক ও গবেষক)',
    email: 'akashdaraz994@gmail.com',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bio: 'আকাশ ইসলামিক সেন্টার ও মাইন্ডস্কোপের প্রতিষ্ঠাতা ও প্রধান লেখক। কুরআনীয় গবেষণা, নৈতিক মূল্যবোধ ও মনস্তত্ত্বের সমন্বয়ে কাজ করছেন।',
    role: 'admin',
    brandPreference: 'islamic',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'admin-akash-2',
    displayName: 'আকাশ (অ্যাডমিনিস্ট্রেটর)',
    email: 'akash994220@gmail.com',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bio: 'আকাশ ইসলামিক সেন্টার ও মাইন্ডস্কোপের প্রতিষ্ঠাতা ও প্রশাসক।',
    role: 'admin',
    brandPreference: 'islamic',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const INITIAL_POSTS: Post[] = [
  // --- BRAND A: আকাশ ইসলামিক সেন্টার (ISLAMIC POSTS) ---
  {
    id: 'post-islamic-1',
    title: 'সালাতে খুশু ও একাগ্রতা: হৃদয়ের গভীর প্রশান্তি অর্জনের উপায়',
    slug: 'art-of-khushoo-salah-presence-heart',
    excerpt: 'যান্ত্রিক অভ্যাসের বাইরে গিয়ে সালাতে আল্লাহর সান্নিধ্য, গভীর একাগ্রতা (খুশু) এবং অন্তরের পরম প্রশান্তি অর্জনের কুরআন ও সুন্নাহভিত্তিক বাস্তব দিকনির্দেশনা।',
    coverImage: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=1000&auto=format&fit=crop&q=80',
    type: 'article',
    brand: 'islamic',
    body: [
      {
        id: 'b-1',
        type: 'heading',
        content: 'দৈনন্দিন জীবনের কোলাহল থেকে আত্মিক আশ্রয়',
        level: 2,
      },
      {
        id: 'b-2',
        type: 'text',
        content: 'সালাত কেবল কিছু শারীরিক ক্রিয়াকলাপের সমষ্টি নয়; বরং এটি পার্থিব জীবনের ব্যস্ততা ও মানসিক ক্লান্তির মাঝে আল্লাহর সাথে সরাসরি সংযোগ স্থাপনের এক অনন্য মাধ্যম। প্রতিদিনের নোটিফিকেশন আর তীব্র অস্থিরতার যুগে জায়নামাজে দাঁড়ানো সৃষ্টি ও স্রষ্টার মাঝে এক নিবিড় সম্পর্ক স্থাপন করে।',
      },
      {
        id: 'b-3',
        type: 'quote',
        content: 'নিশ্চয়ই মুমিনরা সফলকাম হয়েছে, যারা তাদের সালাতে বিনম্র ও একাগ্র (খুশুযুক্ত)।',
        caption: 'সূরা আল-মুমিনূন [২৩:১-২]',
      },
      {
        id: 'b-4',
        type: 'heading',
        content: 'সালাতে একাগ্রতা ফিরিয়ে আনার ৩টি কার্যকর পদক্ষেপ',
        level: 3,
      },
      {
        id: 'b-5',
        type: 'text',
        content: '১. সালাতপূর্ব প্রস্তুতি: তাকবিরে তাহরিমা বলার পূর্বে দুই মিনিট নীরবতা পালন করুন। আপনি কার সামনে দাঁড়াচ্ছেন তা অন্তরে অনুধাবন করুন।\n২. অর্থ বুঝে ধীরস্থির তেলাওয়াত: সূরা আল-ফাতিহা প্রতিটি আয়াত আলাদা করে পাঠ করুন এবং অনুধাবন করুন আল্লাহ আপনার কথার উত্তর দিচ্ছেন।\n৩. সিজদায় দীর্ঘ সময় অতিবাহিত করা: শারীরিক দিক থেকে সিজদাহ হচ্ছে সবচেয়ে বিনম্র ভঙ্গি, আর আধ্যাত্মিক দিক থেকে এটিই আল্লাহর সবচেয়ে নৈকট্য লাভের স্থান।',
      },
      {
        id: 'b-6',
        type: 'divider',
        content: '',
      },
      {
        id: 'b-7',
        type: 'callout',
        content: 'হযরত আনাস (রা.) থেকে বর্ণিত, রাসূলুল্লাহ (সা.) ইরশাদ করেছেন: "সালাতে আমার চোখের শীতলতা রাখা হয়েছে।" আল্লাহ আমাদের সালাতকে চোখের শীতলতা ও অন্তরের প্রশান্তি বানিয়ে দিন।',
      },
    ],
    tags: ['সালাত', 'খুশু', 'আত্মশুদ্ধি', 'কুরআন'],
    authorId: 'admin-akash',
    authorName: 'আকাশ (পরিচালক ও গবেষক)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'published',
    scheduledFor: null,
    likeCount: 48,
    commentCount: 4,
    viewCount: 420,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'post-islamic-2',
    title: 'সূরা আল-কাহফ: ঈমানের ৪টি কঠিন পরীক্ষা ও সমসাময়িক সুরক্ষা',
    slug: 'surah-al-kahf-four-trials-contemporary-relevance',
    excerpt: 'সূরা আল-কাহফে বর্ণিত চারটি ঘটনা—ঈমানের পরীক্ষা, সম্পদের পরীক্ষা, জ্ঞানের পরীক্ষা এবং ক্ষমতার পরীক্ষা থেকে আধুনিক জীবনের আত্মিক সুরক্ষার পথনির্দেশ।',
    coverImage: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=1000&auto=format&fit=crop&q=80',
    type: 'video',
    brand: 'islamic',
    youtubeUrl: 'https://www.youtube.com/watch?v=712fSg5W_Wc',
    transcript: 'আসসালামু আলাইকুম ওয়া রাহমাতুল্লাহ। আজকের এই বিশেষ পাঠে আমরা সূরা আল-কাহফের গভীর দর্শন নিয়ে আলোচনা করব। রাসূলুল্লাহ (সা.) জুমার দিন এই সূরাটি তেলাওয়াত করার ব্যাপারে বিশেষভাবে তাগিদ দিয়েছেন। এর কারণ হলো, এই সূরায় মানুষের জীবনের সবচেয়ে জটিল ৪টি ফেতনা বা পরীক্ষার কথা উল্লেখ করা হয়েছে: আসহাবে কাহাফের ঘটনায় দ্বীনের পরীক্ষা, দুই বাগান মালিকের ঘটনায় সম্পদের পরীক্ষা, মূসা (আ.) ও খিজির (আ.)-এর ঘটনায় জ্ঞানের পরীক্ষা এবং যুলকারনাইনের ঘটনায় ক্ষমতার পরীক্ষা। প্রতিটি ফেতনার বিপরীতে কুরআনে আত্মিক প্রতিরক্ষার সঠিক দিকনির্দেশনা প্রদান করা হয়েছে।',
    studyMaterials: [
      {
        id: 'mat-1',
        title: 'সূরা আল-কাহফ বিশ্লেষণ হ্যান্ডআউট (PDF গাইড)',
        url: 'https://archive.org/download/surah-kahf-study-guide.pdf',
        type: 'pdf',
      },
      {
        id: 'mat-2',
        title: 'তাদাব্বুরে কুরআন নোটস ও রেফারেন্স তালিকা',
        url: 'https://quran.com/18',
        type: 'notes',
      },
    ],
    body: [
      {
        id: 'b-8',
        type: 'heading',
        content: 'দাজ্জালের ফেতনা ও সূরা কাহফের সম্পর্ক',
        level: 2,
      },
      {
        id: 'b-9',
        type: 'text',
        content: 'কেন রাসূলুল্লাহ (সা.) বলেছেন যে ব্যক্তি সূরা আল-কাহফের প্রথম দশটি আয়াত মুখস্থ রাখবে সে দাজ্জালের ফেতনা থেকে রক্ষা পাবে? কারণ দাজ্জালের মূল প্রলোভনগুলো তৈরি হবে অন্ধ বস্তুবাদ, জ্ঞান অহংকার ও ক্ষমতা লিপ্সার সমন্বয়ে। এই সূরায় আল্লাহ তাআলা সেই সমস্ত পার্থিব ছলনার মুখোশ উন্মোচন করেছেন।',
      },
    ],
    tags: ['সূরা আল-কাহফ', 'কুরআন লেকচার', 'ঈমান', 'জীবনদর্শন'],
    authorId: 'admin-akash',
    authorName: 'আকাশ (পরিচালক ও গবেষক)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'published',
    scheduledFor: null,
    likeCount: 65,
    commentCount: 6,
    viewCount: 610,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    publishedAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'post-islamic-3',
    title: 'কুরআন অধ্যয়নের সঠিক দৃষ্টিভঙ্গি: নিছক তিলাওয়াত থেকে অন্তরে ধারণ',
    slug: 'quran-study-mindset-reflection-tadabbur',
    excerpt: 'কুরআন অবতীর্ণ হয়েছে মানুষের অন্তরের পরিশুদ্ধি ও জীবনের সঠিক দিকনির্দেশনার জন্য। কীভাবে তাদাব্বুর বা গভীর ভাবনার মাধ্যমে কুরআনকে নিজের জীবনের সাথে যুক্ত করবেন।',
    coverImage: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?w=1000&auto=format&fit=crop&q=80',
    type: 'article',
    brand: 'islamic',
    body: [
      {
        id: 'b-10',
        type: 'heading',
        content: 'কুরআন তেলাওয়াতের তিনটি প্রধান স্তর',
        level: 2,
      },
      {
        id: 'b-11',
        type: 'text',
        content: '১. বিশুদ্ধ উচ্চারণ ও তাজবীদের সাথে পাঠ।\n২. অর্থ ও শানে নুযুল অনুধাবন।\n৩. তাদাব্বুর বা নিজের জীবনের প্রেক্ষাপটে আয়াতসমূহের গভীর অনুধাবন ও বাস্তবায়ন।',
      },
      {
        id: 'b-12',
        type: 'quote',
        content: 'তবে কি তারা কুরআন নিয়ে গভীর চিন্তা করে না? নাকি তাদের অন্তরে তালা দেওয়া রয়েছে?',
        caption: 'সূরা মুহাম্মদ [৪৭:২৪]',
      },
    ],
    tags: ['কুরআন শিক্ষা', 'তাদাব্বুর', 'নৈতিকতা'],
    authorId: 'admin-akash',
    authorName: 'আকাশ (পরিচালক ও গবেষক)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'published',
    scheduledFor: null,
    likeCount: 31,
    commentCount: 2,
    viewCount: 290,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },

  // --- BRAND B: মাইন্ডস্কোপ এডুকেশন (PSYCHOLOGY & EDUCATION POSTS) ---
  {
    id: 'post-psych-1',
    title: 'নিউরোপ্লাস্টিসিটি ও অভ্যাস গঠন: মস্তিষ্ক কীভাবে নিজেকে পুনর্গঠন করে',
    slug: 'neuroplasticity-habit-formation-brain-rewires-itself',
    excerpt: 'আধুনিক স্নায়ুবিজ্ঞান প্রমাণ করেছে যে মস্তিষ্ক কোনো স্থির কাঠামো নয়। কীভাবে ইচ্ছাশক্তি ও ধারাবাহিক চর্চার মাধ্যমে ক্ষতিকর অভ্যাস ভেঙে নতুন নিউরাল পাথওয়ে তৈরি করবেন।',
    coverImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=1000&auto=format&fit=crop&q=80',
    type: 'article',
    brand: 'psychology',
    body: [
      {
        id: 'b-13',
        type: 'heading',
        content: 'মস্তিষ্কের অভিযোজন ক্ষমতা ও নিউরোপ্লাস্টিসিটি',
        level: 2,
      },
      {
        id: 'b-14',
        type: 'text',
        content: 'একসময় বিজ্ঞানীরা বিশ্বাস করতেন যে প্রাপ্তবয়স্ক হওয়ার পর মানুষের মস্তিষ্কের গঠন স্থায়ী হয়ে যায়। তবে আধুনিক স্নায়ুবিজ্ঞান এই ধারণা সম্পূর্ণ পরিবর্তন করেছে। যেকোনো বয়সেও নতুন চিন্তা, নতুন শিক্ষা এবং অভ্যাসের মাধ্যমে মস্তিষ্ক তার নিউরনের সংযোগগুলো নতুন করে গড়ে তুলতে পারে।',
      },
      {
        id: 'b-15',
        type: 'callout',
        content: '"যেসকল নিউরন একসাথে উদ্দীপিত হয়, তারা একসাথে সংযুক্ত হয়" — ডোনাল্ড হেবের এই সূত্রটিই অভ্যাস গঠনের মূল ভিত্তি।',
      },
      {
        id: 'b-16',
        type: 'heading',
        content: 'অভ্যাস লুপের ৩টি প্রধান উপাদান',
        level: 3,
      },
      {
        id: 'b-17',
        type: 'text',
        content: '১. সংকেত বা কিউ (Cue): যে পরিবেশ বা অনুভূতি অভ্যাসের সূচনা করে।\n২. রুটিন (Routine): প্রকৃত আচরণ বা কাজটি করা।\n৩. পুরস্কার বা রিওয়ার্ড (Reward): ডোপামিন নিঃসরণের মাধ্যমে মস্তিষ্কে তৃপ্তি অনুভূতির সৃষ্টি।',
      },
    ],
    tags: ['নিউরোসায়েন্স', 'অভ্যাস গঠন', 'মনস্তত্ত্ব', 'উৎপাদনশীলতা'],
    authorId: 'admin-akash',
    authorName: 'আকাশ (পরিচালক ও গবেষক)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'published',
    scheduledFor: null,
    likeCount: 52,
    commentCount: 5,
    viewCount: 530,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'post-psych-2',
    title: 'ডিজিটাল যুগে গভীর মনোযোগ (Deep Work) ও ডোপামিন ব্যবস্থাপনা',
    slug: 'deep-work-digital-age-dopamine-focus',
    excerpt: 'নিয়ত নোটিফিকেশন আর শর্ট-ফর্ম কনটেন্টের মধ্যে কীভাবে বিভ্রান্তিমুক্ত গভীর কাজের অভ্যাস গড়ে তুলবেন এবং মানসিক ক্লান্তি দূর করবেন।',
    coverImage: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=1000&auto=format&fit=crop&q=80',
    type: 'video',
    brand: 'psychology',
    youtubeUrl: 'https://www.youtube.com/watch?v=gT_u1PZ5F9M',
    transcript: 'আজকের ক্লাসে আমরা আলোচনা করব মনোযোগের অর্থনীতি (Attention Economy) এবং কার্যক্ষমতা সম্পর্কে। স্মার্টফোন ও সামাজিক মাধ্যমের অ্যালগরিদম আমাদের মস্তিষ্কের স্বাভাবিক ডোপামিন সাইকেলকে বিঘ্নিত করছে। ফলে দীর্ঘমেয়াদী ও গভীর কাজ করার সক্ষমতা কমে যাচ্ছে। আমরা শিখব কীভাবে ৯০ মিনিটের টাইম-ব্লকিং এবং পরিবেশগত নিয়ন্ত্রণের মাধ্যমে চরম একাগ্রতা অর্জন করা সম্ভব।',
    studyMaterials: [
      {
        id: 'mat-3',
        title: 'ডিপ ওয়ার্ক টাইম ব্লকিং শিট (PDF ওয়ার্কবুক)',
        url: 'https://archive.org/download/deep-work-framework.pdf',
        type: 'pdf',
      },
      {
        id: 'mat-4',
        title: 'মনোযোগ ও ডোপামিন নিয়ন্ত্রণ চেকলিস্ট',
        url: 'https://mindscope.edu/resources/focus-checklist',
        type: 'notes',
      },
    ],
    body: [
      {
        id: 'b-18',
        type: 'heading',
        content: 'মনোযোগ বিকেন্দ্রীকরণের মূল কারণ ও প্রতিকার',
        level: 2,
      },
      {
        id: 'b-19',
        type: 'text',
        content: 'মাল্টিটাস্কিং একটি বিভ্রান্তিকর মিথ। মস্তিষ্ক মূলত দ্রুত এক কাজ থেকে অন্য কাজে স্যুইচ করে, যাকে বলা হয় অ্যাটেনশন রেসিডিউ (Attention Residue)। এতে মানসিক শক্তি দ্রুত ক্ষয় হয়। একক কাজে পূর্ণ মনোযোগ দেওয়াই সাফল্যের ভিত্তি।',
      },
    ],
    tags: ['ডিপ ওয়ার্ক', 'মনোযোগ', 'শিক্ষা', 'উৎপাদনশীলতা'],
    authorId: 'admin-akash',
    authorName: 'আকাশ (পরিচালক ও গবেষক)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'published',
    scheduledFor: null,
    likeCount: 41,
    commentCount: 3,
    viewCount: 460,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'post-psych-3',
    title: 'কগনিটিভ রিফ্রেমিং: অতিরিক্ত চিন্তা ও উদ্বেগ নিয়ন্ত্রণের বিজ্ঞানসম্মত পদ্ধতি',
    slug: 'cognitive-reframing-anxiety-overthinking-solutions',
    excerpt: 'কগনিটিভ বিহেভিওরাল থেরাপির (CBT) অন্যতম শক্তিশালী কৌশল হলো কগনিটিভ রিফ্রেমিং। অবচেতন মনের নেতিবাচক চিন্তার প্যাটার্ন চিহ্নিত করে বাস্তববাদী দৃষ্টিভঙ্গি গড়ে তুলুন।',
    coverImage: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=1000&auto=format&fit=crop&q=80',
    type: 'article',
    brand: 'psychology',
    body: [
      {
        id: 'b-20',
        type: 'heading',
        content: 'চিন্তা কখনোই চরম সত্য নয়',
        level: 2,
      },
      {
        id: 'b-21',
        type: 'text',
        content: 'আমাদের মনের ভাবনাগুলো বাস্তবতার হুবহু প্রতিচ্ছবি নয়; এগুলো কেবল মস্তিষ্কের তৈরি করা কিছু ধারণা। কগনিটিভ রিফ্রেমিং আপনাকে সাহায্য করে যেকোনো নেতিবাচক পরিস্থিতিকে বিকল্প ইতিবাচক ও যুক্তিযুক্ত দৃষ্টিকোণ থেকে দেখতে।',
      },
      {
        id: 'b-22',
        type: 'quote',
        content: 'মানুষকে ঘটনা আঘাত করে না, বরং ঘটনার প্রতি তার দৃষ্টিভঙ্গিই তাকে প্রভাবিত করে।',
        caption: 'এপিকটেটাস (দার্শনিক ও মনস্তত্ত্ববিদ)',
      },
    ],
    tags: ['কগনিটিভ থেরাপি', 'উদ্বেগ নিরাময়', 'মানসিক স্বাস্থ্য'],
    authorId: 'admin-akash',
    authorName: 'আকাশ (পরিচালক ও গবেষক)',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'published',
    scheduledFor: null,
    likeCount: 39,
    commentCount: 2,
    viewCount: 380,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    publishedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
];

export const INITIAL_COMMENTS: CommentItem[] = [
  {
    id: 'comm-1',
    postId: 'post-islamic-1',
    userId: 'reader-1',
    userName: 'মুহাম্মদ আব্দুল্লাহ',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    text: 'জাযাকাল্লাহ খাইরান। সালাতে সিজদায় দীর্ঘ সময় কাটানো এবং সূরা ফাতিহা ধীরস্থিরে পাঠ করার পরামর্শটি সত্যি অন্তরে দাগ কেটেছে।',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    likes: 12,
  },
  {
    id: 'comm-2',
    postId: 'post-psych-1',
    userId: 'reader-2',
    userName: 'তানভীর আহমেদ',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    text: 'অভ্যাস লুপের কিউ ও রিওয়ার্ডের বৈজ্ঞানিক ব্যাখ্যা খুব চমৎকার লেগেছে। আমাদের প্রত্যেকের এই বিষয়ে সচেতন হওয়া প্রয়োজন।',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    likes: 8,
  },
];
